# Generated by Django 3.2.15 on 2022-08-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220817_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='inviteMarried_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maleName', models.CharField(max_length=200)),
                ('femaleName', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('clock', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
