# Generated by Django 3.2.15 on 2022-08-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220817_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemarried_request',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
